spring:
  application:
    name: spring-config-server
  profiles:
    active: local,dev,prod,qa
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhi020290/spring-boot-config-server
          search-paths: config-files/payment/
server:
  port: 9090

management:
  security:
    enabled: false
