server:
    port: 8888

spring:
    cloud:
        config:
            server:
                git:
                    uri: E:/myworkspace/spring-boot-config-server.git
                    searchPaths: cloud-config
    profiles:
        active: dev
